package codegen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// RenderKotlinTypes emits Kotlin data classes (types only, no client wrapper).
// Designed to be compatible with onyx-cloud-client usage.
func RenderKotlinTypes(schemaJSON []byte, pkg string) (string, error) {
	var parsed SchemaParsed
	if err := json.Unmarshal(schemaJSON, &parsed); err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	if len(parsed.Entities) == 0 {
		return "", fmt.Errorf("schema has no entities")
	}

	var b strings.Builder
	b.WriteString("// Code generated by onyx gen --kotlin; DO NOT EDIT.\n\n")

	if strings.TrimSpace(pkg) != "" {
		b.WriteString("package ")
		b.WriteString(pkg)
		b.WriteString("\n\n")
	}

	needsDate := false
	for _, ent := range parsed.Entities {
		for _, a := range ent.Attributes {
			if isTimeType(a.Type) {
				needsDate = true
				break
			}
		}
	}
	if needsDate {
		b.WriteString("import java.util.Date\n\n")
	}

	for _, ent := range parsed.Entities {
		if ent.Name == "" {
			continue
		}
		b.WriteString("data class ")
		b.WriteString(ent.Name)
		b.WriteString("(\n")
		for _, attr := range ent.Attributes {
			kt := mapKotlinType(attr.Type, attr.IsNullable)
			b.WriteString("  val ")
			b.WriteString(attr.Name)
			b.WriteString(": ")
			b.WriteString(kt)
			if attr.IsNullable {
				b.WriteString(" = null")
			}
			b.WriteString(",\n")
		}
		for i, r := range ent.Resolvers {
			if strings.TrimSpace(r.Name) == "" {
				continue
			}
			b.WriteString("  val ")
			b.WriteString(r.Name)
			b.WriteString(": Any? = null")
			if i < len(ent.Resolvers)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}

	// Tables constants
	b.WriteString("object Tables {\n")
	for _, ent := range parsed.Entities {
		if ent.Name == "" {
			continue
		}
		b.WriteString("  const val ")
		b.WriteString(ent.Name)
		b.WriteString(" = \"")
		b.WriteString(ent.Name)
		b.WriteString("\"\n")
	}
	b.WriteString("}\n")

	return b.String(), nil
}

func mapKotlinType(schemaType string, nullable bool) string {
	t := strings.ToLower(strings.TrimSpace(schemaType))
	var base string
	switch t {
	case "string", "text", "uuid":
		base = "String"
	case "number", "int", "integer", "float", "double", "long", "short", "byte", "decimal":
		base = "Double"
	case "bool", "boolean":
		base = "Boolean"
	case "date", "datetime", "timestamp", "timestamptz":
		base = "Date"
	case "json", "object", "record", "map", "embeddedobject":
		base = "Any"
	default:
		base = "Any"
	}
	if nullable {
		return base + "?"
	}
	return base
}

func isTimeType(schemaType string) bool {
	switch strings.ToLower(strings.TrimSpace(schemaType)) {
	case "date", "datetime", "timestamp", "timestamptz":
		return true
	default:
		return false
	}
}
