// Code generated by onyx gen --kotlin; DO NOT EDIT.

package onyx

import java.util.Date

data class AuditLog(
  val action: String? = null,
  val actorId: String? = null,
  val changes: Any? = null,
  val dateTime: Date? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null,
  val id: String? = null,
  val metadata: Any? = null,
  val requestId: String? = null,
  val resource: String? = null,
  val status: String? = null,
  val targetId: String? = null,
  val tenantId: String? = null,
)

data class Permission(
  val createdAt: Date? = null,
  val deletedAt: Date? = null,
  val description: String? = null,
  val id: String? = null,
  val name: String? = null,
  val updatedAt: Date? = null,
)

data class Role(
  val createdAt: Date? = null,
  val deletedAt: Date? = null,
  val description: String? = null,
  val id: String? = null,
  val isSystem: Boolean? = null,
  val name: String? = null,
  val updatedAt: Date? = null,
  val permissions: Any? = null,
  val rolePermissions: Any? = null
)

data class RolePermission(
  val createdAt: Date? = null,
  val id: String? = null,
  val permissionId: String? = null,
  val roleId: String? = null,
  val permission: Any? = null,
  val role: Any? = null
)

data class User(
  val createdAt: Date? = null,
  val deletedAt: Date? = null,
  val email: String? = null,
  val id: String? = null,
  val isActive: Boolean? = null,
  val lastLoginAt: Date? = null,
  val updatedAt: Date? = null,
  val username: String? = null,
  val profile: Any? = null,
  val roles: Any? = null,
  val userRoles: Any? = null
)

data class UserProfile(
  val address: Any? = null,
  val age: Double? = null,
  val avatarUrl: String? = null,
  val bio: String? = null,
  val createdAt: Date? = null,
  val deletedAt: Date? = null,
  val firstName: String? = null,
  val id: String? = null,
  val lastName: String? = null,
  val phone: String? = null,
  val updatedAt: Date? = null,
  val userId: String? = null,
)

data class UserRole(
  val createdAt: Date? = null,
  val id: String? = null,
  val roleId: String? = null,
  val userId: String? = null,
  val role: Any? = null
)

object Tables {
  const val AuditLog = "AuditLog"
  const val Permission = "Permission"
  const val Role = "Role"
  const val RolePermission = "RolePermission"
  const val User = "User"
  const val UserProfile = "UserProfile"
  const val UserRole = "UserRole"
}
